#!/bin/bash
# Meant to be run DIRECTLY from a fresh archiso live cd. Try typing, for example:
# [root@archiso]$ dhcpcd eth0
# [root@archiso]$ . <(wget https://raw.github.com/twomen/proterozoic/master/bootstrap-this -qLO-)

# Then you probably want to run this:
# root 123m~$ aif -p enzymes/polymerase -d
echo bootstrapping for the 2011.08.19 live cd...

mkdir -p /tmp/pkgcache
[ -L /var/cache/pacman/pkg ] || {
	 rm -rfv /var/cache/pacman/pkg
	 ln -s /tmp/pkgcache /var/cache/pacman/pkg
}

GITURL=https://raw.github.com/twomen/proterozoic/master

rm -f /etc/profile.d/locale.sh
mv -f /etc/rc.conf{,.original}
mv -f /etc/pacman.conf{,.original}
wget $GITURL/usr/share/ppz/default/rc.conf		-qO	/etc/rc.conf
wget $GITURL/etc/pacman.d/mirrorlist.otown		-qO	/etc/pacman.d/mirrorlist.otown.tmp
wget $GITURL/usr/share/ppz/default/pacman.conf	-qO	/etc/pacman.conf
sed -i \
	 -e 's/^IgnorePkg = /\0linux/ig' \
	 -e s/otown/otown.tmp/ig									/etc/pacman.conf
sed -i \
	 -e s/%SET_TYPE%/desktop/ig \
	 -e s/%SET_HOSTNAME%/archiso/ig							/etc/rc.conf

[ "$(uname -m)" = i686 ] && sed -i 's/\[multilib\]/#\0/ig' /etc/pacman.conf

pacman --noprogressbar --noconfirm --needed -Sqy pacman
pacman --noprogressbar --noconfirm --needed -Sqf filesystem
pacman --noprogressbar --noconfirm --needed -Squ smartmontools base-devel
pacman --noprogressbar --noconfirm --needed -Squ proterozoic
pacman --noprogressbar --noconfirm --needed -Sqcc

sed -i s/otown.tmp/otown/ig									/etc/pacman.conf
rm -f /etc/pacman.d/mirrorlist.otown.tmp
