#!/bin/bash

# someday ... get this to set some ext3 vars and tune2fs

GITURL=https://raw.github.com/yardenac/proterozoic/master

mv -f /etc/pacman.conf{,.original}
curl $GITURL/usr/share/ppz/default/ppz.conf		-so	/etc/ppz.conf
curl $GITURL/etc/pacman.d/mirrorlist.otown		-so	/etc/pacman.d/mirrorlist.otown.tmp
curl $GITURL/usr/share/ppz/default/pacman.conf	-so	/etc/pacman.conf
sed -i s/otown/otown.tmp/ig									/etc/pacman.conf
sed -i \
	 -e s/%SET_TYPE%/linode/ig \
	 -e 's/32m$/128m/ig' \
	 -e 's/^#*:[\t ]*sync.*$/#&/ig' \
	 -e 's/^#*:[\t ]*user[\t ]*ex.*$/#&/ig'				/etc/ppz.conf

echo "${SS_HOSTNAME}" >| /etc/hostname

cat > /etc/fstab <<-EOF
	/dev/xvda / ext3 rw,noatime,nodiratime,barrier=0,commit=5,errors=remount-ro 0 1
EOF

echo "Forking md5sum for entropy..."
ionice -c 3 nice -n 19 md5sum /dev/xvda &>/dev/null &
md5sumpid=$!
pacman-key --init
kill -SIGTERM $md5sumpid

pacman-key --populate archlinux

pacman --noprogressbar --noconfirm --needed -Sqyyu

cat >| /etc/mkinitcpio.conf <<-EOF
	HOOKS="base udev autodetect fsck ppz_tmp"
EOF
pacman --noprogressbar --noconfirm --needed -Sq proterozoic
sed -i s/otown.tmp/otown/ig /etc/pacman.conf
pacman --noprogressbar --noconfirm --needed -Sq linux-linode

rm -f \
	 /etc/mkinitcpio.conf.pacorig \
	 /etc/pacman.d/mirrorlist.{otown.tmp,pacnew}

mv -f /etc/protocols{.pacnew,}
mv -f /etc/services{.pacnew,}

# how to get proper "kernel name" in install file?

. /usr/share/ppz/bash.functions
. /usr/share/ppz/bash.functions.install
static_networking_from_runtime /
grex /etc/resolv.conf > /etc/resolv.conf.override

rc.d start mysqld
echo $'\n\n'"$SS_MYSQLPASS"$'\n'"$SS_MYSQLPASS"$'\n\n\n\n\n' | mysql_secure_installation
rc.d stop mysqld

myip=$(ifconfig | awk '/^lo/ {exit} $1 ~ /^inet$/ {print $2}')
fqhn=$(dig -x $myip +short)
sed -i 's/^\(ServerName \).*$/\1'$fqhn'/i'	/etc/httpd/conf/site-specific.conf

askyn "reboot now?" && shutdown -hP now
