#!/bin/bash

# someday ... get this to set some ext3 vars and tune2fs

GITURL=https://raw.github.com/yardenac/proterozoic/master

mv -f /etc/pacman.conf{,.original}
curl $GITURL/usr/share/ppz/default/ppz.conf		-so	/etc/ppz.conf
curl $GITURL/etc/pacman.d/mirrorlist.otown		-so	/etc/pacman.d/mirrorlist.otown.tmp
curl $GITURL/usr/share/ppz/default/pacman.conf	-so	/etc/pacman.conf
sed -i s/otown/otown.tmp/ig									/etc/pacman.conf
sed -i \
	 -e s/%SET_TYPE%/linode/ig \
	 -e 's/32m$/128m/ig' \
	 -e 's/^#*:[\t ]*sync.*$/#&/ig' \
	 -e 's/^#*:[\t ]*user[\t ]*ex.*$/#&/ig'				/etc/ppz.conf

echo "${SS_HOSTNAME}" >| /etc/hostname

cat > /etc/fstab <<-EOF
	/dev/xvda / ext3 rw,noatime,nodiratime,barrier=0,commit=5,errors=remount-ro 0 1
EOF

case "$(uname -m)" in
	 i686)  	sed -i 's/^\[multilib\]$/#&/ig'			/etc/pacman.conf;;
	 x86_64)	sed -i 's/^##*\(\[multilib\]\)$/\1/ig'	/etc/pacman.conf;;
esac

echo "Forking md5sum for entropy..."
haveged -w 1024
pacman-key --init
pkill haveged

pacman-key --populate archlinux

systemctl disable dbus.service

pacman --noprogressbar --noconfirm --needed -Sqyyu

cat >| /etc/mkinitcpio.conf <<-EOF
	HOOKS="base udev autodetect modconf block filesystems fsck ppz_tmp"
EOF
pacman --noprogressbar --noconfirm --needed -Sq proterozoic
sed -i s/otown.tmp/otown/ig /etc/pacman.conf
pacman --noprogressbar --noconfirm --needed -Sq linux-linode

rm -f \
	 /etc/{fstab,pacman.conf,locale.gen}.pacnew \
	 /etc/pacman.d/mirrorlist.{otown.tmp,pacnew}

# how to get proper "kernel name" in install file?

. /usr/share/ppz/bash.functions
. /usr/share/ppz/bash.functions.install
static_networking_from_runtime >| /etc/conf.d/network

mkdir /etc/ssh/keys
echo "${SS_PUBKEY}" >| /etc/ssh/keys/eu

systemctl enable ip{,6}tables network
systemctl disable getty@tty1.service

askyn "reboot now?" && systemctl poweroff
