#!/bin/bash

# someday ... get this to set some ext3 vars and tune2fs

GITURL=--no-check-certificate\ https://raw.github.com/twomen/proterozoic/master

rm -f /etc/profile.d/locale.sh
mv -f /etc/rc.conf{,.original}
mv -f /etc/pacman.conf{,.original}
wget $GITURL/usr/share/ppz/default/rc.conf		-qO	/etc/rc.conf
wget $GITURL/etc/pacman.d/mirrorlist.otown		-qO	/etc/pacman.d/mirrorlist.otown.tmp
wget $GITURL/usr/share/ppz/default/pacman.conf	-qO	/etc/pacman.conf
sed -i s/otown/otown.tmp/ig									/etc/pacman.conf
sed -i \
	 -e s/%SET_HOSTNAME%/${SS_HOSTNAME}/ig \
	 -e s/%SET_TYPE%/linode/ig \
	 -e s/=UTC/=xen/ig \
	 -e 's/32m$/128m/ig' \
	 -e 's/\(DAEMONS=([^)]*\))/\1 @mysqld @httpd)/i' \
	 -e 's/\(OPEN_PORTS=([^)]*\))/\1 80)/i' \
	 -e 's/^#*:[\t ]*sync.*$/#&/ig' \
	 -e 's/^#*:[\t ]*user[\t ]*ex.*$/#&/ig'				/etc/rc.conf

cat > /etc/fstab <<-EOF
	/dev/xvda / ext3 rw,noatime,nodiratime,barrier=0,commit=5,errors=remount-ro 0 1
EOF

pacman --noprogressbar --noconfirm --needed -Sqyy pacman

echo "Forking md5sum for entropy..."
ionice -c 3 nice -n 19 md5sum /dev/xvda &>/dev/null &
md5sumpid=$!
pacman-key --init
kill -SIGTERM $md5sumpid

pacman --noprogressbar --noconfirm --needed -Sqf filesystem
pacman --noprogressbar --noconfirm --needed -Squ base-devel tor privoxy \
	 bitlbee weechat mysql php php-apache php-ssh apache
cat >| /etc/mkinitcpio.conf <<-EOF
	HOOKS="base udev autodetect fsck ppz_tmp"
EOF
pacman --noprogressbar --noconfirm --needed -Sq proterozoic
sed -i s/otown.tmp/otown/ig /etc/pacman.conf
pacman --noprogressbar --noconfirm --needed -Sq linux-linode

rm -f \
	 /etc/pacman.d/mirrorlist.otown.tmp \
	 /etc/{locale.gen,pacman.d/mirrorlist,pacman.conf,rc.conf}.pacnew

# how to get proper "kernel name" in install file?

. /usr/share/ppz/bash.functions
. /usr/share/ppz/bash.functions.install
static_networking_from_runtime /
grex /etc/resolv.conf > /etc/resolv.conf.override

rc.d start mysqld
echo $'\n\n'"$SS_MYSQLPASS"$'\n'"$SS_MYSQLPASS"$'\n\n\n\n\n' | mysql_secure_installation
rc.d stop mysqld

myip=$(ifconfig | awk '/^lo/ {exit} $1 ~ /^inet$/ {print $2}')
fqhn=$(dig -x $myip +short)
sed -i 's/^\(ServerName \).*$/\1'$fqhn'/i'	/etc/httpd/conf/site-specific.conf

askyn "reboot now?" && shutdown -hP now
