#!/bin/bash
[ -a ./package-this ] || {
	 echo "You have to run this from the same directory!"
	 exit 1
}
. usr/share/ppz/bash.functions


[ "$1" ] && REPO="$1" || croak USAGE: ./package-this [repo-directory]
[ -d ${REPO} ] || croak ${REPO} not mounted!

#no other way to suppress syslog non-root errors, even just doing --syntax-only!
{ syslog-ng -svvf etc/syslog-ng/syslog-ng.conf.ppz; echo SIBBOLETH:$?; } 2>&1 | {
	 while read LINE; do
		  [[ ${LINE} =~ ^syslog-ng:\ Error\ setting\ (file\ number\ limit|capabilities) ]] && continue
		  [[ ${LINE} =~ ^SIBBOLETH ]] && exit ${LINE#SIBBOLETH:}
		  echo ${LINE}
	 done
} || croak BAD SYSLOG SYNTAX!

makepkg -cd \
	 && PF=$(ls -1tr *.pkg.tar.xz | tail -n 1) \
	 && {
	 for arch in i686 x86_64; do
		  cp $PF ${REPO}/$arch/ || continue
		  repo-add ${REPO}/$arch/hir.db.tar.gz ${REPO}/$arch/$PF
	 done
	 rm -f $PF
}

git diff HEAD --quiet -- bootstrap-this etc/pacman.d/mirrorlist.otown usr/share/ppz/default-{rc,pacman}.conf \
	 || echo_red "Bootstrap files have changed, you probably want to update git!"
