#!/bin/bash
[ -a ./package-this ] || {
	 echo "You have to run this from the same directory!"
	 exit 1
}
. etc/bash.functions


[ "$1" ] && REPO="$1" || croak USAGE: ./package-this [repo-directory]
[ -d ${REPO} ] || croak ${REPO} not mounted!

#no other way to suppress syslog non-root errors, even just doing --syntax-only!
{ syslog-ng -svvf etc/syslog-ng/syslog-ng.conf.ppz; echo SIBBOLETH:$?; } 2>&1 | {
	 while read LINE; do
		  [[ ${LINE} =~ ^syslog-ng:\ Error\ setting\ (file\ number\ limit|capabilities) ]] && continue
		  [[ ${LINE} =~ ^SIBBOLETH ]] && exit ${LINE#SIBBOLETH:}
		  echo ${LINE}
	 done
} || croak BAD SYSLOG SYNTAX!

makepkg -c \
	 && PF=$(ls -1tr *.pkg.tar.xz | tail -n 1) \
	 && mv $PF ${REPO}/ \
	 && repo-add ${REPO}/hir.db.tar.gz ${REPO}/$PF

git diff HEAD --quiet -- bootstrap-this etc/{rc.conf{.ppz,.basics},pacman.{conf.bootstrap,d/mirrorlist.otown}} \
	 || echo_red "Bootstrap files have changed, you probably want to update git!"
