#!/bin/bash
# <UDF name="ss_hostname" label="hostname" />
echo bootstrapping for the 2010.05 linode image...
this_pacman() {
	 pacman --config /etc/pacman.conf --noprogressbar --noconfirm "$@"
}
GITURL=https://raw.github.com/twomen/proterozoic/master

mv -f /etc/rc.conf{,.original}
mv -f /etc/sudoers{,.original}
mv -f /etc/pacman.conf{,.original}
wget $GITURL/usr/share/ppz/default/locale.gen	-qO	/etc/locale.gen
wget $GITURL/usr/share/ppz/default/rc.conf		-qO	/etc/rc.conf
wget $GITURL/etc/pacman.d/mirrorlist.otown		-qO	/etc/pacman.d/mirrorlist.otown.tmp
wget $GITURL/usr/share/ppz/default/pacman.conf	-qO	/etc/pacman.conf
sed -i s/otown/otown.tmp/ig									/etc/pacman.conf
sed -i \
	 -e s/%SET_HOSTNAME%/${SS_HOSTNAME}/ig \
	 -e s/=UTC/=xen/ig \
	 -e 's`^[\t ]*/.*___[a-f0-9]*___.*\.\(png\|bin\.gz\)$``ig' \
	 -e 's/^SSH_USERS.*$/SSH_USERS=(root)/ig'				/etc/rc.conf
locale-gen
sed -i 's/^SyncFirst/#\0/' /etc/pacman.conf
this_pacman -Sqy pacman glibc
pacman-db-upgrade
sed -i 's/^#\(SyncFirst\)/\1/' /etc/pacman.conf
this_pacman -Squ
echo 'utmp:x::' >> /etc/gshadow
mv -f /etc/bash.bashrc{.pacnew,}
this_pacman -Sq mkinitcpio
cat > /etc/mkinitcpio.conf <<-EOF
	HOOKS="base udev autodetect ppz_tmp"
EOF
mv -f /etc/hosts{.pacnew,}
this_pacman -Sq proterozoic
sed -i s/otown.tmp/otown/ig /etc/pacman.conf
this_pacman -Sq linux-linode

rm -f \
	 /etc/pacman.d/mirrorlist.otown.tmp \
	 /etc/{gshadow,locale.gen,securetty,hosts,inittab,pacman.d/mirrorlist}.pacnew

# how to get proper "kernel name" in install file?

add_hook() { :; }
. /etc/rc.conf
. /etc/rc.d/functions.d/ppz
. /usr/share/ppz/bash.functions.install
#custom_iptables_rules
static_networking_from_runtime /
grex /etc/resolv.conf > /etc/resolv.conf.override
askyn "reboot now?"
shutdown -hP now
