#!/bin/bash
# <UDF name="ss_hostname" label="hostname" />
# <UDF name="ss_encuser"  label="encrypted user" />
echo bootstrapping for the 2010.05 linode image...

this_pacman() {
	 pacman --config /tmp/pacman.conf.ppz --noprogressbar --noconfirm "$@"
}
GITURL=https://raw.github.com/twomen/proterozoic/master

mv -f /etc/rc.conf{,.original}
mv -f /etc/sudoers{,.original}
wget $GITURL/usr/share/ppz/default-rc.conf		-qO	/etc/rc.conf
wget $GITURL/etc/pacman.d/mirrorlist.otown		-qO	/etc/pacman.d/mirrorlist.otown.tmp
wget $GITURL/usr/share/ppz/default-pacman.conf	-qO	/tmp/pacman.conf.ppz
sed -i s/otown/otown.tmp/ig									/tmp/pacman.conf.ppz
sed -i \
	 -e s/%SET_HOSTNAME%/${SS_HOSTNAME}/ig \
	 -e s/%SET_ENCUSER%/${SS_ENCUSER}/ig \
	 -e s/=UTC/=xen/ig \
	 -e 's/^SSH_USERS.*$/SSH_USERS=(root)/ig'				/etc/rc.conf

cat > /etc/locale.gen <<-EOF
		en_US.UTF-8 UTF-8
		en_US ISO-8859-1
		es_US.UTF-8 UTF-8
		es_US ISO-8859-1
		he_IL.UTF-8 UTF-8
		he_IL ISO-8859-8
		iw_IL.UTF-8 UTF-8
		iw_IL ISO-8859-8
		de_DE.UTF-8 UTF-8
		de_DE ISO-8859-1
		EOF
locale-gen

this_pacman -Sqy pacman
pacman-db-upgrade
this_pacman -Sqyu
this_pacman -Sq mkinitcpio
sed -i 's/^\(HOOKS="[^"]*\)"/\1 ppz_tmp"/ig' /etc/mkinitcpio.conf
this_pacman -Sq proterozoic
cat > /etc/mkinitcpio.conf <<-EOF
	HOOKS="base udev autodetect ppz_tmp"
EOF
this_pacman -Sq linux-linode

rm /tmp/pacman.conf.ppz /etc/pacman.d/mirrorlist.otown.tmp

# pacnew list:
# /etc/locale.gen
# /etc/bash.bashrc
# gshadow hosts securetty inittab rc.conf
# /etc/pacman.d/mirrorlist
# 
# modules not found: dm-crypt, fuse
# why does integrity get called twice??
# why do the remote sync files not happen together

add_hook() { :; }
. /etc/rc.conf
. /etc/rc.d/functions.d/ppz
. /usr/share/ppz/bash.functions.install
custom_iptables_rules
static_networking_from_runtime /
useradd -lMNd /media/encuser -u 54345 -s /usr/bin/womb ${SS_ENCUSER}
