#!/bin/bash
# <UDF name="ss_hostname" label="hostname" />

say_and_do()	{ echo DOING: "$@"; "$@"; }
fsls_quote()	{ echo "$@" | sed 's_/_\\/_gi'; }

setbashvar() { # USAGE: setbashvar VAR value /file/path
	 HASHTXT='#\|'
	 OCCS=$(grep -iEc '^[#[:space:]]*'${1}= ${3})
	 [ $OCCS -gt 1 ] && {
		  NOCCS=$(grep -iEc '^[[:space:]]*'${1}= ${3})
		  [ $NOCCS -gt 1 ] && return 1
		  HASHTXT=''
	 }
	 PATTERN=$(fsls_quote "${2}")
	 say_and_do sed -i 's/^\('${HASHTXT}'\s\)*'${1}'=.*$/'${1}'="'"${PATTERN}"'"/i' ${3}
}

setbashvar HOSTNAME			${SS_HOSTNAME}			/etc/rc.conf
setbashvar HARDWARECLOCK	xen						/etc/rc.conf
setbashvar TIMEZONE			America/Los_Angeles	/etc/rc.conf
say_and_do sed -i 's/^\(127.0.0.1.*\)$/\1 '${SS_HOSTNAME}'/' /etc/hosts

say_and_do hostname ${SS_HOSTNAME}

#wget sane mirrorlist

echo -e "\n[hir]\nServer = http://pacman-repo.hirstory.com\n" >> /etc/pacman.conf

pacman -Sy  --noconfirm pacman
pacman-db-upgrade
pacman -Syu --noconfirm
pacman -Sy  --noconfirm proterozoic kernel26-linode
# give k-l ipv6 support

ret_ipaddr() {
	 IPADDR=$(ip -4 address show dev eth0 | grep -iEo '([0-9]{1,3})(\.[0-9]{1,3}){3}/24')
	 echo ${IPADDR%%/*}
}
SS_IPADDR=$(ret_ipaddr)

setbashvar eth0				"eth0 ${SS_IPADDR}      netmask 255.255.255.0" /etc/rc.conf
setbashvar gateway			"eth0 ${SS_IPADDR%.*}.1 netmask 255.255.255.0" /etc/rc.conf
setbashvar routes				gateway					/etc/rc.conf
