#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=$(pidof -xo %PPID /usr/bin/keep-net-up)
case "$1" in
	 start)
		  stat_busy "Starting keep-net-up"
		  [ -z "$PID" ] && /usr/bin/keep-net-up -d &>>/dev/null
		  if [ $? -gt 0 ]; then
				stat_fail
				else
				add_daemon keep-net-up
				stat_done
		  fi
		  ;;
	 stop)
		  stat_busy "Stopping keep-net-up"
		  [ ! -z "$PID" ]  && kill $PID &> /dev/null
		  if [ $? -gt 0 ]; then
				stat_fail
		  else
				rm_daemon keep-net-up
				stat_done
		  fi
		  ;;
	 restart)
		  $0 stop
		  sleep 1
		  $0 start
		  ;;
	 *)
		  echo "usage: $0 {start|stop|restart}"
esac
