#!/bin/bash

do_tmpfs() {
	 mkdir -p /tmp
	 mount -t tmpfs -o defaults,nodev,nosuid,noexec,mode=1777,size=$1,uid=0,gid=0,noauto,noatime,nodiratime shm /tmp
}
ppz_mount_handler() {
	 HOSTNAME=$(cat /etc/hostname)
	 case $HOSTNAME in
		  gabba)			do_tmpfs 5%;; #~12MB
		  scaly)			do_tmpfs 40%;;
		  ediacra|*)	do_tmpfs 12%;;
	 esac
	 case $HOSTNAME in
		  something)	:;; # some_other_mount_handler :)
		  *)				default_mount_handler "$@";;
	 esac
	 mount --move /tmp /new_root/tmp
}
exec_sh_wrapper() {
	 echo ":: Hard break requested...have fun ;)"
	 launch_interactive_shell --exec
}
if [ "${hardbreak}" = "y" ]; then
	 run_hook() {
		  mount_handler=exec_sh_wrapper
	 }
else
	 run_hook() {
		  mount_handler=ppz_mount_handler
	 }
fi
