#!/bin/bash
# <UDF name="ss_hostname" label="hostname" />
# <UDF name="ss_mysqlpass" label="mysqlpass" />
# <UDF name="ss_pubkey" label="pubkey" />

echo "Downloading external stackscript..."

curl https://raw.github.com/yardenac/proterozoic/master/bootstrap-this-linode -sLo /tmp/.btl

echo "Sourcing it..."

. /tmp/.btl

# no need to delete tmpfile because script calls reboot?
rm -rf /tmp/.btl
