#!/bin/bash
# <UDF name="ss_hostname" label="hostname" />
# <UDF name="ss_mysqlpass" label="mysqlpass" />

echo "Downloading external stackscript..."

wget --no-check-certificate \
	 https://raw.github.com/twomen/proterozoic/master/bootstrap-this-linode \
	 -qLO /tmp/.btl

echo "Sourcing it..."

. /tmp/.btl

# no need to delete tmpfile because script calls reboot?
rm -rf /tmp/.btl
