#!/bin/bash
. /etc/rc.conf
. /etc/bash.functions

if [ -e /dev/mapper/$ENC_MAPNAME ]; then
    [ "$1" = "verbose" ] && echo already unencrypted: /dev/mapper/$ENC_MAPNAME
else
    echo uncrypting: /dev/mapper/$ENC_MAPNAME
    /sbin/cryptsetup luksOpen $ENC_DEV $ENC_MAPNAME || do_fail can\'t open luks!
fi
if grep -iq /dev/mapper/$ENC_MAPNAME /etc/mtab; then
    [ "$1" = "verbose" ] && echo already mounted: /dev/mapper/$ENC_MAPNAME
else
    echo mounting: /dev/mapper/$ENC_MAPNAME
	 case $(/sbin/blkid -s TYPE -o value /dev/mapper/$ENC_MAPNAME) in
		  btrfs)	:;;
		  *) /sbin/fsck /dev/mapper/$ENC_MAPNAME || {
					 echo fsck failed ... jsyk
					 read
				};;
	 esac
    /bin/mount -o rw,relatime,nodiratime /dev/mapper/$ENC_MAPNAME $ENC_HOMEDIR
fi
do_edie_cache() {
	 FDIR=/home/fin/fuse
	 if grep -iq $FDIR/aufs /etc/mtab; then
		  [ "$1" = "verbose" ] && echo already mounted: $FDIR/aufs
	 else
		  echo mounting: $FDIR/aufs
		  /bin/mount -t aufs -o br:$FDIR/local=rw:$FDIR/arch-cache=ro,xino=/tmp/.aufs.xino.fin,noauto,noatime,nodiratime,udba=none none $FDIR/aufs
	 fi
}
case $(hostname) in
	 ediacra) do_edie_cache "$@";;
esac
