#!/bin/bash
PATH=/sbin:/bin:/usr/bin

# should not be run directly except from the integrity scripts.
# exists so that users with encrypted homedirs can set them up
# with root privileges. thats the ONLY good reason to write code in here...
# do not use in AIF! pacman installation will call integrity scripts,
# and that is enough.

. /etc/rc.conf
. /usr/share/ppz/bash.functions

am_root || echo "must be root!"

case "$1" in
	 cryptmap)
		  until [ -e /dev/mapper/$enc_mapname ]; do
				if [ -a $tmp_keyfile ]; then
					 cat "$tmp_keyfile" | \
						  cryptsetup luksOpen "$2" $enc_mapname -d - \
						  || croak "luksopen failed with raw key"
				elif [ -a "$enc_keyfile" ]; then
					 usetvar PW "Enter the password for your LUKS key: " '' '' -s \
						  || croak "No password entered"
					 echo "$PW" \
						  | gpg --no-tty --no-mdc-warning --passphrase-fd 0 -qd "$enc_keyfile" \
						  | cryptsetup luksOpen "$2" $enc_mapname -d - \
						  || croak "luksopen failed with gpg'd key"
				else
					 cryptsetup luksOpen "$2" $enc_mapname \
						  || croak "luksopen failed with password"
				fi
		  done;;
	 mount)
		  until grep -iq /dev/mapper/$enc_mapname /etc/mtab; do
				case $(blkid -s TYPE -o value /dev/mapper/$enc_mapname) in
					 btrfs)	:;;
					 *)		fsck /dev/mapper/$enc_mapname
				esac
				(( $? )) && {
					 echo fsck failed ... jsyk
#					 read
				}
				mkdir -p /media/enc
				mount -o rw,relatime,nodiratime /dev/mapper/$enc_mapname $enc_mountpt || croak "mount failed"
				[ -a /media/enc/u ] || cp -r /etc/skel.ppz /media/enc/u
		  done
esac
