#!/bin/bash
. /usr/share/ppz/bash.functions
set_hacks() {
	 set +o noclobber
	 echo 2000 > /sys/module/block/parameters/events_dfl_poll_msecs
	 set -o noclobber
}
resolv_override() {
	 [ -f /etc/resolv.conf.override ] \
		  && rm -f /etc/resolv.conf \
		  && cp -f /etc/resolv.conf{.override,}
}
print_welcome() {
	 : # echo_yellow BOOTING ARCH LINUX / PROTEROZOIC
}
add_hook sysinit_udevsettled	set_hacks
add_hook sysinit_premount		/usr/bin/integrity.ppz
add_hook multi_start				resolv_override
