#!/bin/bash

build() {
    add_file /etc/systemd/system/headerdev.mount.d/local.conf
    add_binary sed
    add_binary systemctl
    add_binary hwinfo
    add_binary lsblk
    add_binary lspci
    add_binary lsusb
    add_binary find
    add_binary udevadm
    add_systemd_unit headerdev.mount
    add_systemd_unit headerdev.service
}
