#!/usr/bin/bash
# [root@archiso]$ systemctl start dhcpcd@*.service || wifi-menu
# [root@archiso]$ . <(wget https://raw.github.com/yardenac/proterozoic/master/bootstraps/archiso -qLO-)
# root 123m~$ /usr/bin/integrity.ppz

sshport=$(( RANDOM + 32767 ))
echo bootstrapping for the 2015.04.01 live cd... ssh port will be $sshport

ionice -c 3 -p $$
renice -n 19 $$

GITURL=https://raw.github.com/yardenac/proterozoic/master

mv -f /etc/pacman.conf{,.original}
wget $GITURL/usr/share/ppz/default/ppz.conf		-qO	/etc/ppz.conf
wget $GITURL/usr/share/ppz/default/pacman.conf	-qO	/etc/pacman.conf
wget $GITURL/etc/pacman.d/mirrorlist.https-only	-qO- | sort -Ruo /etc/pacman.d/mirrorlist.https-only.random
sed -i \
	 -e 's/^IgnorePkg[ =]*/\0 linux /ig' \
	 -e s/https-only/https-only.random/ig 					/etc/pacman.conf
sed -i \
	 -e "s/somename/eu/ig" \
	 -e "s/=(22)/=($sshport)/" \
	 -e s/%SET_TYPE%/desktop/ig								/etc/ppz.conf

[ "$(uname -m)" = i686 ] && sed -i 's/\[multilib\]/#\0/ig' /etc/pacman.conf

GNUPGHOME=/etc/pacman.d/gnupg/ pacman-key -r 3020A074 --keyserver pgp.mit.edu
pacman-key --lsign-key 3020A074
pacman --noconfirm -Rs gnu-netcat
pacman --noconfirm -Syu
pacman --noconfirm -Scc
pacman --noconfirm -S proterozoic
#pacman --noconfirm -S python2 mprime biosdisk-git

gpasswd -a eu wheel
gpasswd -a eu systemd-journal

timedatectl set-timezone America/Los_Angeles
systemctl start ip{,6}tables ntpd

mkdir /etc/ssh/keys
echo 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKZHaN9x2NGws2vXrOduIqUpUVRnqbPAGTZ/SS5YUUCR' \
	 >| /etc/ssh/keys/eu

echo REMINDER: ssh port is $sshport
