#!/usr/bin/bash
# [root@archiso]$ dhcpcd eth0
# [root@archiso]$ . <(wget https://raw.github.com/yardenac/proterozoic/master/bootstraps/archiso -qLO-)
# root 123m~$ /usr/bin/integrity.ppz
echo bootstrapping for the 2014.02.01 live cd...

ionice -c 3 -p $$
renice -n 19 $$

GITURL=https://raw.github.com/yardenac/proterozoic/master

mv -f /etc/pacman.conf{,.original}
wget $GITURL/usr/share/ppz/default/ppz.conf		-qO	/etc/ppz.conf
wget $GITURL/usr/share/ppz/default/pacman.conf	-qO	/etc/pacman.conf
wget $GITURL/etc/pacman.d/mirrorlist.https-only	-qO- | sort -Ruo /etc/pacman.d/mirrorlist.https-only.random
sed -i \
	 -e 's/^IgnorePkg[ =]*/\0 linux /ig' \
	 -e s/https-only/https-only.random/ig 					/etc/pacman.conf
sed -i \
	 -e "s/somename/eu/ig" \
	 -e s/%SET_TYPE%/desktop/ig								/etc/ppz.conf

[ "$(uname -m)" = i686 ] && sed -i 's/\[multilib\]/#\0/ig' /etc/pacman.conf

pacman-key -r 3020A074 --keyserver pgp.mit.edu
pacman-key --lsign-key 3020A074
pacman --noconfirm -Syu proterozoic python2
pacman --noconfirm -Scc

gpasswd -a eu wheel
gpasswd -a eu systemd-journal

timedatectl set-timezone America/Los_Angeles
systemctl start ip{,6}tables

mkdir /etc/ssh/keys
echo 'ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBACr529+8mpJaMbfeXKAYFba9nhnv6nTlDd7VwnTSQda2aJXuwOu/aRD8GImPhu789x/KZFCALi9wTboRUYEprEKAwBQzl1vhqs7ZRniieF0b8MeOJNt3mEw+dXokuApne93VM+3QO20Vu26MQy7YN43pUqELI7zyUdSPMRVpmmCwWo6aA==' \
	 >| /etc/ssh/keys/eu
